defaults:
  - _self_
  - override hydra/launcher:  local
  - override hydra/output:  local

# snapshot
save_snapshot: false
load_snap: ""

# replay buffer
num_workers: 10
batch_size: 32 
train_steps: 4001
eval_freq: 250

# misc
seed: 1
device: cuda

# experiment
experiment: train_vip
wandbuser: 
wandbproject: 

# data
dataset:
datapath: 
doaug: "none"

agent:
  _target_: vip.VIP
  device: ${device}
  lr: 1e-4
  hidden_dim: 3
  size: 18
  l2weight: 0.0
  l1weight: 0.0
  num_negatives: 0
